Feat/rework settings pages
FidelCly/dashboard pull request #1137
Opened 2023-08-14 08:26 UTC by JeremCy

### Changes proposed in this pull request
- add edit shop form 
- add edit user form

2023-08-14 11:46 UTC, sihamais requested changes

2023-08-14 11:46 UTC, sihamais commented on src/Components/html/Sidebar.tsx
>          </li>
Pourquoi avoir déplacé les infos du user dans la sidebar ? C'est censé être dans la navbar non ?

2023-08-14 11:46 UTC, sihamais commented on src/pages/settings/index.tsx
> +  };
Stylé !

2023-08-14 11:46 UTC, sihamais commented on src/pages/settings/index.tsx
> +          <ShopUpdateForm />
Quand tu update, il n'y a pas de toas  pour informer que l'update a bien marché

2023-08-14 11:46 UTC, sihamais commented on src/Components/form/User.form.tsx
> +      setValue('birthday', user?.birthday);
La valeur du birthday est pas affichée, ça reste toujours `mm/dd/yyyy` même quand il y en a une

2023-08-14 11:46 UTC, sihamais commented on src/pages/settings/index.tsx
> -        <Navbar />
Pourquoi avoir supprimé toute la navbar, on veut quand même garder le nom de la personne et le bouton pour se déco

2023-08-15 12:01 UTC, JeremCy commented on src/pages/settings/index.tsx
> +          <ShopUpdateForm />
done

2023-08-15 12:08 UTC, JeremCy commented on src/Components/form/User.form.tsx
> +      setValue('birthday', user?.birthday);
done

2023-08-15 12:25 UTC, sihamais approved these changes

2023-08-15 12:25 UTC, merged